# Generated by Django 4.2.9 on 2024-02-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_digital_product_date_added_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ManyToManyField(blank=True, related_name='collections', to='store.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Collections',
        ),
    ]
