# Generated by Django 4.2.9 on 2024-02-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='twocolumnsection',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
