# Generated by Django 4.2.9 on 2024-02-02 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_twocolumnsection_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twocolumnsection',
            old_name='complete',
            new_name='text_on_right',
        ),
    ]
