# Generated by Django 4.2.9 on 2024-02-02 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_complete_twocolumnsection_text_on_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagebanner',
            name='mobile',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
